# Generated by Django 3.1.2 on 2020-11-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gespharx_id', models.IntegerField()),
                ('din', models.CharField(max_length=30)),
                ('generic_name', models.CharField(max_length=30)),
            ],
        ),
    ]
